# Generated by Django 4.2.1 on 2023-05-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
